config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :episodes
  root 'episodes#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
	
	has_attached_file :mp3
	validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] }, :file_name => { :matches => [/mp3\Z/] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :update, :destroy]
  before_action :set_episode, only: [:show, :edit, :update, :destroy]
  before_action :find_episode, only: [:show, :edit, :update, :destroy]


  def index
    @episodes = Episode.all.order('created_at DESC')
  end

  def show
  end

  def new
    @episode = Episode.new
  end

  def edit
  end

  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:title, :description, :mp3)
    end

    def find_episode
      @episode = Episode.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/episodes/_form.html.erb
<%= form_for(episode) do |f| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.trix_editor :description %>
  </div>

  <div class="form-group">
    <%= f.label :mp3 %>
    <%= f.file_field :mp3 %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h1><em><span class="logo">Begin.fm</span></em></h1>
      <lead>A show for beginners in web development, design, photography, and other creative fields.</lead>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <ul class="nav text-center">
        <li>
          <a href="mailto:dan85.cardenas@gmail.com?subject=Hello">Say Hi</a>
        </li> 
        <% if admin_signed_in? %>
          <span class="nav-line-break">|</span>
          <li><%= link_to 'New Episode', new_episode_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% @episodes.each do |episode| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 episode-listings">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-1 episode-listings-content">
            <ul>
              <li><h4><%= episode.title %></h4></li>
              <% if admin_signed_in? %>
                <li>
                  <p>
                    <%= link_to 'Edit', edit_episode_path(episode), class: "btn btn-primary" %>
                    <%= link_to 'Delete', episode, class: "btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
                  </p>
                </li>
              <% end %>
              <li>
                <p><%= episode.description.truncate(140).html_safe %></p>
              </li>
              <li><p><%= link_to 'Listen to this episode', episode %></p></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/episodes/new.html.erb
<div class="container">
	<div class="row">
	<div class="col-md-6 col-md-offset-3">
			<h1>New Episode</h1>
			<%= render 'form', episode: @episode %>
			<%= link_to 'Back', episodes_path %>
		</div>
	</div>
</div>

app/views/episodes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-offset-1 col-xs-10 col-xs-offset-1">
      <ul class="nav">
        <li><h4><em><span class="logo"><%= link_to "Begin.fm", root_path %><h4></strong></em></h4></li>
        <li class="nav-home"><%= link_to 'Home', root_path %></li>
        <span class="nav-line-break">|</span>
        <li><%= link_to 'Say Hi', "#" %></li>
      </ul>
    </div>
  </div>
	<div class="row">
		<div class="col-xs-offset-1 col-xs-10 col-xs-offset-1 episode-content">
			<h4><%= @episode.title %></h4>
      <% if admin_signed_in? %>
        <p>
  				<%= link_to 'Edit', edit_episode_path(@episode) %> |
  				<%= link_to 'Back', episodes_path %>
  			<p>
      <% end %>
      <div id="jquery_jplayer_1" class="jp-jplayer" data-mp3="<%= @episode.mp3.url %>"></div>
      <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
        <div class="jp-type-single">
          <div class="jp-gui jp-interface">
            <ul class="jp-controls">
              <li>
                <a href="javascript:;" class="jp-play" tabindex="1"><span class="glyphicon glyphicon-play"></span></a>
              </li>
              <li>
                <a href="javascript:;" class="jp-pause" tabindex="1"><span class="glyphicon glyphicon-pause"></span></a>
              </li>
              <li>
                <a href="javascript:;" class="jp-mute" tabindex="1" title="mute"><span class="glyphicon glyphicon-volume-up"></span></a>
              </li>
              <li>
                <a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute"><span class="glyphicon glyphicon-volume-off"></span></a>
              </li>
            </ul>

            <div class="jp-progress">
              <div class="jp-seek-bar">
                <div class="jp-play-bar"></div>
              </div>
            </div>

            <div class="jp-time-holder">
              <div class="jp-current-time"></div>
            </div>

            <div class="jp-volume-bar">
              <div class="jp-volume-bar-value"></div>
            </div>

            <div class="jp-no-solution">
              <span>Update Required</span>
              To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
          <div class="trix-content"><%= @episode.description.html_safe %></div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-offset-2 col-xs-8 col-xs-offset-2">
          <ul class="nav-footer">
            <hr>
            <li class="nav-home"><%= link_to 'Home', root_path %></li>
            <span class="nav-line-break">|</span>
            <li>
              <a href="mailto:dan85.cardenas@gmail.com?subject=Hello">Say Hi
              </a>
            </li>
          </ul>
        </div>
      </div>
		</div>
	</div>
</div>
<script>
  $(document).ready(function(){
    $("#jquery_jplayer_1").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: $(this).data('mp3'),
        });
      },
      swfPath: "/js",
      supplied: "mp3"
    });
  });
</script>

app/views/home/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 text-center">
			<h1>HELLO</h1>
			<lead>Copy here...</lead>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<ul class="nav text-center">
				<li>Home</li> |
				<li>Say Hi</li>
			</ul>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="card card-block">
				<div class="row">
					<div class="col-xs-8 col-xs-offset-1">
						<h4 class="card-title">Episode #</h4>
						<p class="card-text">Copy here...</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Begin.fm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:900" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>